/**
 * Spec 064 — the single typed source of per-route SEO head data for the five
 * PUBLIC routes (the only ones prerendered at build time and listed in
 * sitemap.xml). Consumed by:
 *   - `src/prerender-entry.tsx` (build-time head injection via
 *     vite-prerender-plugin)
 *   - `src/seo/publicFiles.test.ts` (locks public/sitemap.xml + robots.txt +
 *     the IndexNow key to this source)
 *
 * Private app routes are deliberately NOT here: they are client-rendered only,
 * Disallowed in robots.txt, and excluded from the sitemap.
 */

export const SITE_ORIGIN = 'https://almamesh.com';

/**
 * The original brand OG card (1200x630) — the FALLBACK for any path that is
 * not a listed public route (public routes carry their own card, below).
 */
export const OG_IMAGE_URL = `${SITE_ORIGIN}/og-card.png`;

/**
 * Per-route OG cards: `public/og/<slug>.png` (1200x630), design-siblings of the
 * brand card, generated by `scripts/generate-og-images.mjs` and COMMITTED — the
 * build never depends on the generator. Root maps to the `home` slug so the
 * file has a real basename; every other route reuses its path slug.
 */
export function ogSlugFor(path: string): string {
  return path === '/' ? 'home' : path.replace(/^\//, '');
}

/** Absolute og:image URL for a route — per-route card, or the brand fallback. */
export function ogImageUrlFor(path: string): string {
  return getRouteHead(path) ? `${SITE_ORIGIN}/og/${ogSlugFor(path)}.png` : OG_IMAGE_URL;
}

/** Shape vite-prerender-plugin serializes into `<head>` (`{type, props}`). */
export interface HeadElement {
  readonly type: string;
  readonly props: Record<string, string>;
}

export interface RouteHead {
  /** App route path, e.g. `/welcome`. */
  readonly path: string;
  /** Unique `<title>` (≤ 70 chars). */
  readonly title: string;
  /** Unique meta description (50–160 chars, search-snippet sized). */
  readonly description: string;
  /** Absolute canonical URL on almamesh.com. */
  readonly canonical: string;
}

function route(path: string, title: string, description: string): RouteHead {
  return {
    path,
    title,
    description,
    canonical: path === '/' ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${path}`,
  };
}

export const PUBLIC_ROUTE_HEADS: readonly RouteHead[] = [
  route(
    '/',
    'AlmaMesh — Free Local-First Vedic Astrology in Your Browser',
    'Free Vedic (sidereal) astrology computed entirely in your browser. No accounts, no server, offline after first load. Open-source engine, honest readings.',
  ),
  route(
    '/welcome',
    'Welcome to AlmaMesh — Vedic Astrology That Respects Your Data',
    'Meet AlmaMesh: authentic Vedic charts — planets, nakshatras, dashas — calculated on your device, free forever. No sign-up, no scams, no data collection.',
  ),
  route(
    '/privacy',
    'Privacy Policy — AlmaMesh',
    'AlmaMesh runs in your browser — your birth date and time never leave your device. Only birthplace search and optional AI touch the network. Privacy by design.',
  ),
  route(
    '/terms',
    'Terms of Service — AlmaMesh',
    'The terms for using AlmaMesh, the free open-source Vedic astrology app: no accounts, honest disclaimers, and astrology offered as reflection, not fact.',
  ),
  route(
    '/data-deletion',
    'Data Deletion — AlmaMesh',
    'Your data lives only in your browser. Deleting it is a local action you control — clear it in-app or via browser storage. No server copies exist.',
  ),
];

export const PUBLIC_ROUTE_PATHS: readonly string[] = PUBLIC_ROUTE_HEADS.map((h) => h.path);

/**
 * Cloudflare-Pages output layout for a prerendered public route — the build
 * outputs a FLAT `<slug>.html` (never a nested `<slug>/index.html`) so the
 * no-slash canonical URL is the one CF Pages serves with HTTP 200.
 *
 * Why flat matters (the canonical bug this fixes): CF Pages serves a nested
 * `welcome/index.html` at the TRAILING-SLASH URL and 308-redirects the no-slash
 * form to it (`/welcome` -> 308 -> `/welcome/`). But the canonical tag, `og:url`
 * (see `route()` above) AND `sitemap.xml` all point at the NO-slash `/welcome`.
 * The declared canonical therefore redirected away from itself, so Google could
 * never settle it and the pages stayed unindexed. A flat `welcome.html` is
 * served at `/welcome` with a 200 (CF 308-normalizes the `/` and `.html`
 * variants back to it), so all four signals finally agree on the no-slash URL.
 *
 * Returned paths are relative to the build `outDir`, matching Rollup asset
 * `fileName`s (no leading slash). Root stays `index.html`.
 */
export function prerenderOutputFile(path: string): string {
  return path === '/' ? 'index.html' : `${path.replace(/^\//, '')}.html`;
}

/** Absolute-from-outDir flat file for every public route (root -> index.html). */
export const PRERENDER_OUTPUT_FILES: readonly string[] =
  PUBLIC_ROUTE_PATHS.map(prerenderOutputFile);

/**
 * Every private app surface, by prefix — the robots.txt Disallow list.
 * (`/life` covers `/life/:domain`, `/mesh` covers `/mesh/:memberId`, etc.)
 */
export const PRIVATE_ROUTE_PREFIXES: readonly string[] = [
  '/dashboard',
  '/onboarding',
  '/predictive',
  '/report',
  '/mesh',
  '/rectify',
  '/settings',
  '/life',
];

export function getRouteHead(path: string): RouteHead | undefined {
  return PUBLIC_ROUTE_HEADS.find((h) => h.path === path);
}

/**
 * The full per-route head-tag set (description + canonical + Open Graph +
 * Twitter card) in vite-prerender-plugin's `{type, props}` element shape.
 * The `<title>` travels separately (the plugin's `head.title` replaces the
 * template title). The SoftwareApplication JSON-LD stays static in
 * `index.html` — valid site-level entity data on every page.
 */
export function headElementsFor(path: string): HeadElement[] {
  const head = getRouteHead(path);
  if (!head) return [];
  const ogImage = ogImageUrlFor(path);
  const meta = (props: Record<string, string>): HeadElement => ({ type: 'meta', props });
  return [
    meta({ name: 'description', content: head.description }),
    { type: 'link', props: { rel: 'canonical', href: head.canonical } },
    meta({ property: 'og:type', content: 'website' }),
    meta({ property: 'og:site_name', content: 'AlmaMesh' }),
    meta({ property: 'og:title', content: head.title }),
    meta({ property: 'og:description', content: head.description }),
    meta({ property: 'og:url', content: head.canonical }),
    meta({ property: 'og:image', content: ogImage }),
    meta({ property: 'og:image:width', content: '1200' }),
    meta({ property: 'og:image:height', content: '630' }),
    meta({ name: 'twitter:card', content: 'summary_large_image' }),
    meta({ name: 'twitter:title', content: head.title }),
    meta({ name: 'twitter:description', content: head.description }),
    meta({ name: 'twitter:image', content: ogImage }),
  ];
}
