"""Golden parity regression for the chart engine (DE421 + fixed reference_date).

The in-browser Pyodide engine must produce output byte-identical to CPython.
This test pins a canonical golden generated by the trusted CPython oracle
(`calculate_sidereal_context`) so both the browser parity test and this backend
regression test compare against the same numbers.

Charts are made reproducible by injecting a FIXED `reference_date` (otherwise the
"current" Vimshottari maha dasha reads the wall clock). Floats are canonicalized
to 6 decimals recursively so trivial last-bit noise never trips the guard.

Regenerate the golden (only when the engine intentionally changes):
    uv run python -m tests.test_chart_golden
"""

import json
from datetime import UTC, datetime
from pathlib import Path

from almamesh.calculations import PlanetName, calculate_sidereal_context
from almamesh.schemas.astrology import SiderealContext

# Fixed "now" so the current maha dasha (and thus the chart) is reproducible.
FIXED_REFERENCE_DATE = datetime(2025, 1, 1, 0, 0, 0, tzinfo=UTC)

# (datetime ISO UTC, latitude, longitude) -- the 5 canonical parity fixtures.
FIXTURES: list[tuple[str, float, float]] = [
    ("1990-01-15T12:00:00+00:00", 28.6139, 77.2090),  # Delhi
    ("1985-07-23T04:30:00+00:00", 19.0760, 72.8777),  # Mumbai
    ("2000-12-31T23:59:00+00:00", 40.7128, -74.0060),  # NYC
    ("1972-03-10T08:15:00+00:00", 51.5074, -0.1278),  # London
    ("2010-06-21T18:00:00+00:00", -33.8688, 151.2093),  # Sydney
    # Diverse-timezone coverage for the UTC-conversion fix (the chart inputs are
    # already UTC; these lock the half-hour-offset instant and the cusp case).
    ("1988-08-08T01:14:00+00:00", 12.9716, 77.5946),  # Bengaluru cusp (06:44 IST)
    ("2019-11-09T17:45:00+00:00", 35.6895, 139.6917),  # Tokyo (+09:00 instant)
]

GOLDEN_PATH = Path(__file__).parent / "fixtures" / "chart_golden_de421.json"


def _canonicalize(value: object) -> object:
    """Recursively round floats to 6 decimals; preserve bool; sort dict keys."""
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return round(value, 6)
    if isinstance(value, dict):
        return {k: _canonicalize(value[k]) for k in sorted(value)}
    if isinstance(value, list):
        return [_canonicalize(item) for item in value]
    return value


def _chart_for(iso_dt: str, lat: float, lon: float) -> SiderealContext:
    """Run the trusted CPython oracle for one fixture (fixed reference_date)."""
    dt_utc = datetime.fromisoformat(iso_dt)
    return calculate_sidereal_context(dt_utc, lat, lon, reference_date=FIXED_REFERENCE_DATE)


def _canonical_chart(iso_dt: str, lat: float, lon: float) -> object:
    """Canonicalized JSON dump of one fixture's chart."""
    return _canonicalize(_chart_for(iso_dt, lat, lon).model_dump(mode="json"))


def _load_golden() -> dict[str, object]:
    """Load the committed golden fixture as a keyed dict."""
    loaded = json.loads(GOLDEN_PATH.read_text())
    assert isinstance(loaded, dict)
    return loaded


def test_all_fixtures_match_golden() -> None:
    """Every fixture's canonicalized chart equals the committed golden."""
    golden = _load_golden()
    for iso_dt, lat, lon in FIXTURES:
        assert _canonical_chart(iso_dt, lat, lon) == golden[iso_dt]


def test_delhi_reference_signs_are_sane() -> None:
    """Human-sanity guard: a silently-wrong golden would shift these signs."""
    chart = _chart_for(*FIXTURES[0])
    assert chart.lagna.sign.value == "Gemini"
    assert chart.planets[PlanetName.SUN].sign.value == "Capricorn"
    assert chart.planets[PlanetName.MOON].sign.value == "Leo"
    assert chart.dashas.current_maha is not None
    assert chart.dashas.current_maha.lord.value == "rahu"


def _generate_golden() -> None:
    """Regenerate the committed golden from the oracle (run via __main__)."""
    golden = {iso: _canonical_chart(iso, lat, lon) for iso, lat, lon in FIXTURES}
    GOLDEN_PATH.write_text(json.dumps(golden, indent=2, sort_keys=True) + "\n")
    print(f"Wrote {GOLDEN_PATH} ({GOLDEN_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    _generate_golden()
