/**
 * Interpretation store — the on-device, local-first home for the structured
 * `VedicInterpretation` the app generates client-side, keyed by `chartId` and
 * persisted to IndexedDB so a generated reading survives reloads and joins the
 * same crash-atomic personal-data Replace transaction as every other store.
 *
 * No backend, no streaming SSE: unlike the predecessor (which tracked a server
 * stream token-by-token), the WHOLE `VedicInterpretation` is produced in the
 * browser, so this store holds the finished object plus coarse per-section
 * progress for the dashboard to render. Persistence uses the shared personal-
 * data IndexedDB transaction under one key, alongside the chart/profile stores.
 *
 * Callers pass `updatedAt` (an ISO string) explicitly — the store never calls
 * `Date.now()`/`new Date()` itself, keeping it deterministic and easy to test.
 */

import { create, type StateCreator } from 'zustand';
import { createJSONStorage, persist, type StateStorage } from 'zustand/middleware';

import type { ReadingProvenance } from '@almamesh/llm';
import type { VedicInterpretation } from '@almamesh/shared-types';
import { deletionAwareIdbStorage } from './deletionTombstones';

/** Lifecycle of a chart's interpretation generation. */
export type InterpretationStatus = 'idle' | 'generating' | 'complete' | 'error';

/**
 * Deterministic inputs that may have shaped a generated reading.
 *
 * A string means the LLM received predictive facts computed for that exact
 * natal-input/day key. `null` explicitly means the reading was natal-only.
 * An absent `inputProvenance` is legacy/unknown and must not be conflated with
 * natal-only by consumers: older builds could narrate predictive facts without
 * recording which request produced them.
 */
export interface InterpretationInputProvenance {
  readonly predictiveRequestKey: string | null;
}

/** The persisted record for a single chart's interpretation. */
export interface ChartInterpretationEntry {
  readonly status: InterpretationStatus;
  /** The finished structured reading; present once `status === 'complete'`. */
  readonly interpretation?: VedicInterpretation;
  /** Failure message; present once `status === 'error'`. */
  readonly error?: string;
  /** Section key -> completed. Lets the dashboard show progressive progress. */
  readonly sections: Readonly<Record<string, boolean>>;
  /**
   * Section key -> failed. Per-section LLM failures degrade that section to
   * empty while the run still completes; recording them here lets the UI stay
   * honest about the gap (and offer a regenerate) instead of rendering a blank
   * section with no signal. Optional so pre-existing persisted entries load
   * unchanged; cleared by `startInterpretation`.
   */
  readonly failedSections?: Readonly<Record<string, boolean>>;
  /** ISO-8601 timestamp of the last mutation; supplied by the caller. */
  readonly updatedAt?: string;
  /**
   * The display-friendly identity of the resolved LLM provider config that
   * produced this reading (`configProvenance` from `@almamesh/llm`:
   * engine/model/endpoint, NEVER a key). Lets the UI caption the reading
   * ("Generated by <model>") and the dashboard detect "the configured AI
   * changed since this reading was generated" and regenerate. Absent on
   * pre-v3 persisted entries — treated as a mismatch by the consumer.
   */
  readonly provenance?: ReadingProvenance;
  /** Exact predictive input used for this reading, or explicit natal-only. */
  readonly inputProvenance?: InterpretationInputProvenance;
  /** Owning profile, retained across chart regeneration for complete deletion. */
  readonly profileId?: string;
}

/** Ephemeral identity for one generation attempt; never persisted. */
export type InterpretationRunToken = number;

export interface InterpretationStore {
  /** All interpretation entries, keyed by `chartId`. */
  readonly byChart: Readonly<Record<string, ChartInterpretationEntry>>;

  /**
   * Begin generation: status -> 'generating', clearing progress + error. A
   * previously completed reading (and its provenance/updatedAt) is KEPT on the
   * entry — keep-old-until-success — so a regeneration never destroys the
   * reading on screen; only a successful `setInterpretation` replaces it.
   */
  startInterpretation: (chartId: string, profileId?: string) => InterpretationRunToken;
  /** Record that one named section finished (progressive progress). */
  markSectionComplete: (
    chartId: string,
    section: string,
    runToken?: InterpretationRunToken,
  ) => void;
  /** Record that one named section FAILED (degraded to empty; run continues). */
  markSectionFailed: (
    chartId: string,
    section: string,
    runToken?: InterpretationRunToken,
  ) => void;
  /**
   * Store the finished reading: status -> 'complete'. `provenance` is the
   * identity of the config that produced it; omitting it (legacy callers)
   * stores an unattributed reading, which consumers treat as config-mismatched.
   * `inputProvenance` independently records whether the LLM received an exact
   * predictive request or a natal-only chart. Omitting it means legacy/unknown.
   */
  setInterpretation: (
    chartId: string,
    interpretation: VedicInterpretation,
    updatedAt: string,
    provenance?: ReadingProvenance,
    inputProvenance?: InterpretationInputProvenance,
    runToken?: InterpretationRunToken,
  ) => Promise<void>;
  /** Record a failure: status -> 'error'. */
  setError: (chartId: string, error: string, runToken?: InterpretationRunToken) => void;
  /** Read one chart's entry, or `undefined` if none exists. */
  getEntry: (chartId: string) => ChartInterpretationEntry | undefined;
  /** Drop one chart's entry entirely. */
  reset: (chartId: string) => void;
  /** Drop current and historical chart entries owned by one profile. */
  deleteForProfile: (profileId: string, currentChartIds: readonly string[]) => void;
  /** Attribute legacy entries only when current chart/thread ownership is unambiguous. */
  backfillProfileOwnership: (ownersByChart: Readonly<Record<string, string>>) => void;
  /** Drop every chart's entry — the "start fresh" reset. */
  clearAll: () => void;
}

/** A single IndexedDB key holding every interpretation, persisted by zustand. */
export const INTERPRETATION_PERSIST_NAME = 'almamesh-interpretations';

/**
 * Bump when the persisted shape changes; always pair with `migrate`.
 * v2: `VedicInterpretation.summary` went from a bare `string` to a dual-mode
 * `Persona` ({ layman, technical }). The migration normalizes any old string
 * summary into both voices — no regeneration; the old text renders in both.
 * v3: entries gained an optional `provenance` config fingerprint. Purely
 * additive: v2 entries hydrate unchanged with `provenance: undefined` and keep
 * rendering; the dashboard treats the missing fingerprint as a config
 * mismatch and regenerates once when an AI capable of readings is configured.
 * v4: entries gained optional `inputProvenance`, distinguishing an exact
 * predictive request from explicit natal-only generation. Existing entries
 * remain unknown so consumers can fail closed instead of reusing possibly
 * stale predictive prose.
 * v5: entries may carry `profileId` ownership. Legacy ownerless readings are
 * preserved; deletion removes them only when chart/thread ownership proves
 * they belong to the deleted profile.
 */
export const INTERPRETATION_PERSIST_VERSION = 5;

/** The slice of the store that `partialize` actually persists. */
export interface PersistedInterpretationState {
  readonly byChart: Readonly<Record<string, ChartInterpretationEntry>>;
}

/** A plain (non-array) object — the only shape `byChart` may safely take. */
function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/**
 * Defensive hydration: tolerate ANY old/unknown/corrupt persisted blob and
 * always return a valid `{ byChart }`. A returning visitor whose stored reading
 * map is malformed (a string, an array, a missing field) must never crash the
 * dashboard — we fall back to an empty map and the reading regenerates.
 */
export function migrateInterpretationPersistedState(
  persisted: unknown,
  _fromVersion: number,
): PersistedInterpretationState {
  if (!isPlainRecord(persisted)) {
    return { byChart: {} };
  }
  const byChart = persisted.byChart;
  if (!isPlainRecord(byChart)) {
    return { byChart: {} };
  }
  const normalized: Record<string, ChartInterpretationEntry> = {};
  for (const [chartId, entry] of Object.entries(byChart)) {
    const healed = healInterruptedEntry(normalizeEntrySummary(entry));
    if (healed) {
      normalized[chartId] = healed;
    }
  }
  return { byChart: normalized };
}

/**
 * A persisted `status: 'generating'` can never be truly in flight after a
 * reload — streams do not survive page unloads. Left alone it renders an
 * eternal "Generating…" card that the auto-generate effect refuses to replace
 * (a dead-end with no in-app recovery). Heal on every hydrate: a kept reading
 * means the run was a regeneration — surface it as 'complete'; no reading
 * means nothing was ever produced — drop the entry so auto-generate fires.
 */
function healInterruptedEntry(
  entry: ChartInterpretationEntry,
): ChartInterpretationEntry | undefined {
  if (!isPlainRecord(entry) || entry.status !== 'generating') {
    return entry;
  }
  if (entry.interpretation) {
    const { error: _staleError, ...kept } = entry;
    return { ...kept, status: 'complete' };
  }
  return undefined;
}

/**
 * zustand-persist `merge`: runs on EVERY rehydrate (unlike `migrate`, which
 * only runs on a version bump), so same-version reloads also heal interrupted
 * generations. Reuses the defensive migrate pipeline — idempotent for healthy
 * current-shape blobs — and layers the persisted map over the live store so
 * actions survive.
 */
export function mergeInterpretationPersistedState(
  persisted: unknown,
  current: InterpretationStore,
): InterpretationStore {
  const healed = migrateInterpretationPersistedState(persisted, INTERPRETATION_PERSIST_VERSION);
  return { ...current, byChart: healed.byChart };
}

/**
 * v1 -> v2: a persisted `interpretation.summary` may be a bare `string` (the
 * pre-dual-voice shape). Normalize it to a dual-mode `Persona` so the same text
 * renders in both the "For You" and "For Astrologer" voices. Entries with no
 * interpretation, or an already-dual summary, pass through unchanged.
 */
function normalizeEntrySummary(entry: unknown): ChartInterpretationEntry {
  if (!isPlainRecord(entry)) {
    return entry as unknown as ChartInterpretationEntry;
  }
  const interpretation = entry.interpretation;
  if (!isPlainRecord(interpretation) || typeof interpretation.summary !== 'string') {
    return entry as unknown as ChartInterpretationEntry;
  }
  const summary = interpretation.summary;
  return {
    ...(entry as unknown as ChartInterpretationEntry),
    interpretation: {
      ...(interpretation as unknown as VedicInterpretation),
      summary: { layman: summary, technical: summary },
    },
  };
}

/**
 * zustand `StateStorage` backed by localStorage. Outside a browser (SSR, unit
 * tests) localStorage is absent, so every op is a benign no-op and the store
 * simply runs in-memory — persistence is a browser-only enhancement, not a
 * correctness requirement (mirrors the IndexedDB pattern in the other slices).
 */
const interpretationStorage: StateStorage = {
  getItem: async (name) => {
    const durable = await deletionAwareIdbStorage.getItem(name);
    if (durable !== null) return durable;
    const storage = (globalThis as { localStorage?: Partial<Storage> }).localStorage;
    const legacy = typeof storage?.getItem === 'function' ? storage.getItem(name) : null;
    if (legacy === null) return null;
    await deletionAwareIdbStorage.setItem(name, legacy);
    if (typeof storage?.removeItem === 'function') storage.removeItem(name);
    return deletionAwareIdbStorage.getItem(name);
  },
  setItem: (name, value) => deletionAwareIdbStorage.setItem(name, value),
  removeItem: async (name) => {
    await deletionAwareIdbStorage.removeItem(name);
    const storage = (globalThis as { localStorage?: Partial<Storage> }).localStorage;
    if (typeof storage?.removeItem === 'function') storage.removeItem(name);
  },
};

async function persistInterpretationSnapshot(state: InterpretationStore): Promise<void> {
  await useInterpretationStore.persist.getOptions().storage?.setItem(
    INTERPRETATION_PERSIST_NAME,
    { state: { byChart: state.byChart }, version: INTERPRETATION_PERSIST_VERSION },
  );
}

/** The entry a chart starts from before any section has completed. */
const EMPTY_ENTRY: ChartInterpretationEntry = { status: 'idle', sections: {} };

/** Read the current entry for a chart, defaulting to the empty entry. */
function entryOf(
  byChart: Record<string, ChartInterpretationEntry>,
  chartId: string,
): ChartInterpretationEntry {
  return byChart[chartId] ?? EMPTY_ENTRY;
}

/** Pure: write one chart's entry, leaving the rest of the map untouched. */
function withEntry(
  byChart: Record<string, ChartInterpretationEntry>,
  chartId: string,
  entry: ChartInterpretationEntry,
): Record<string, ChartInterpretationEntry> {
  return { ...byChart, [chartId]: entry };
}

export const interpretationStoreCreator: StateCreator<InterpretationStore> = (set, get) => {
  const activeRuns = new Map<string, InterpretationRunToken>();
  let nextRunToken = 0;

  const acceptsRun = (chartId: string, runToken?: InterpretationRunToken): boolean =>
    runToken === undefined || activeRuns.get(chartId) === runToken;

  return {
    byChart: {},

    startInterpretation: (chartId, profileId) => {
      nextRunToken += 1;
      const runToken = nextRunToken;
      activeRuns.set(chartId, runToken);
      set((state) => {
        const current = entryOf(state.byChart, chartId);
        // Keep-old-until-success: progress, error and failed sections reset, but
        // a previously completed reading (with its provenance + timestamp) stays
        // on the entry so the UI keeps showing it while — and after, if — the
        // new run fails. A brand-new chart starts from the empty entry as before.
        const kept =
          current.interpretation !== undefined
            ? {
                interpretation: current.interpretation,
                ...(current.provenance !== undefined ? { provenance: current.provenance } : {}),
                ...(current.inputProvenance !== undefined
                  ? { inputProvenance: current.inputProvenance }
                  : {}),
                ...(current.updatedAt !== undefined ? { updatedAt: current.updatedAt } : {}),
              }
            : {};
        const owner = profileId ?? current.profileId;
        return {
          byChart: withEntry(state.byChart, chartId, {
            status: 'generating',
            sections: {},
            ...kept,
            ...(owner !== undefined ? { profileId: owner } : {}),
          }),
        };
      });
      return runToken;
    },

    markSectionComplete: (chartId, section, runToken) => {
      set((state) => {
        if (!acceptsRun(chartId, runToken)) {
          return state;
        }
        const current = entryOf(state.byChart, chartId);
        const sections = { ...current.sections, [section]: true };
        return { byChart: withEntry(state.byChart, chartId, { ...current, sections }) };
      });
    },

    markSectionFailed: (chartId, section, runToken) => {
      set((state) => {
        if (!acceptsRun(chartId, runToken)) {
          return state;
        }
        const current = entryOf(state.byChart, chartId);
        const failedSections = { ...current.failedSections, [section]: true };
        return { byChart: withEntry(state.byChart, chartId, { ...current, failedSections }) };
      });
    },

    setInterpretation: async (
      chartId,
      interpretation,
      updatedAt,
      provenance,
      inputProvenance,
      runToken,
    ) => {
      set((state) => {
        if (!acceptsRun(chartId, runToken)) {
          return state;
        }
        const current = entryOf(state.byChart, chartId);
        // `provenance` always overwrites (including with undefined): the stored
        // fingerprint must describe THIS reading, never a stale predecessor's.
        const entry: ChartInterpretationEntry = {
          ...current,
          status: 'complete',
          interpretation,
          error: undefined,
          updatedAt,
          provenance,
          inputProvenance,
        };
        return { byChart: withEntry(state.byChart, chartId, entry) };
      });
      await persistInterpretationSnapshot(get());
    },

    setError: (chartId, error, runToken) => {
      set((state) => {
        if (!acceptsRun(chartId, runToken)) {
          return state;
        }
        const current = entryOf(state.byChart, chartId);
        return {
          byChart: withEntry(state.byChart, chartId, { ...current, status: 'error', error }),
        };
      });
    },

    getEntry: (chartId) => get().byChart[chartId],

    reset: (chartId) => {
      activeRuns.delete(chartId);
      set((state) => {
        const byChart = { ...state.byChart };
        delete byChart[chartId];
        return { byChart };
      });
    },

    deleteForProfile: (profileId, currentChartIds) => {
      const targetIds = new Set(currentChartIds);
      set((state) => {
        const byChart: Record<string, ChartInterpretationEntry> = {};
        for (const [chartId, entry] of Object.entries(state.byChart)) {
          if (targetIds.has(chartId) || entry.profileId === profileId) {
            activeRuns.delete(chartId);
          } else {
            byChart[chartId] = entry;
          }
        }
        for (const chartId of targetIds) {
          activeRuns.delete(chartId);
        }
        return { byChart };
      });
    },

    backfillProfileOwnership: (ownersByChart) => {
      set((state) => ({
        byChart: Object.fromEntries(
          Object.entries(state.byChart).map(([chartId, entry]) => {
            const owner = ownersByChart[chartId];
            return [
              chartId,
              entry.profileId === undefined && owner !== undefined
                ? { ...entry, profileId: owner }
                : entry,
            ];
          }),
        ),
      }));
    },

    clearAll: () => {
      activeRuns.clear();
      set({ byChart: {} });
    },
  };
};

/**
 * Interpretation store, persisted to IndexedDB under `almamesh-interpretations`.
 */
export const useInterpretationStore = create<InterpretationStore>()(
  persist<InterpretationStore, [], [], PersistedInterpretationState>(interpretationStoreCreator, {
    name: INTERPRETATION_PERSIST_NAME,
    version: INTERPRETATION_PERSIST_VERSION,
    migrate: migrateInterpretationPersistedState,
    merge: mergeInterpretationPersistedState,
    storage: createJSONStorage(() => interpretationStorage),
    partialize: (state) => ({ byChart: state.byChart }),
  }),
);
