/**
 * ONE rule, checked ACROSS the language boundary.
 *
 * The report prints a word and a percentage on the same line ("45% · moderate").
 * The word is computed in Python (`backend/src/almamesh/yogas/factors.grade_for`)
 * and rendered in TypeScript (`lib/yogaStrength`). A backend-only test cannot
 * see the rendered word, and a frontend-only test cannot see the engine's rule —
 * so a divergence between them is exactly what neither side's suite catches. It
 * shipped: the engine graded on `net >= 2 / net <= -1` while the UI banded on
 * `pct >= 75 / >= 40`, and three yogas on the reference chart printed
 * "WEAK" beside "45% · MODERATE" in public.
 *
 * This test closes that seam with a REAL engine artifact. It reads the committed
 * golden — 58 yogas across 7 charts, produced by CPython `calculate_sidereal_
 * context` and regenerated by `uv run python -m tests.test_chart_golden` — pushes
 * each yoga through the actual render path the report uses, and asserts the word
 * the reader sees agrees with the number printed beside it.
 *
 * The cut points below are restated as TypeScript literals on purpose. They are
 * NOT imported: they are the published contract (rigor-upgrade §A.1) that both
 * implementations are measured against, so neither can quietly move them.
 *
 * Break the property, not the form: restore `net >= 2 / net <= -1` in Python's
 * `grade_for`, regenerate the golden, and this TypeScript suite goes red on 14
 * of the 58 yogas.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import type { YogaData } from '@almamesh/browser/types';
import { hasStrength, yogaStrength } from '../yogaStrength';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../../../../..');
const GOLDEN_PATH = resolve(root, 'backend/tests/fixtures/chart_golden_de421.json');

// The published §A.1 percentage -> word cut points, restated as literals.
const STRONG_MIN_PCT = 75;
const MODERATE_MIN_PCT = 40;

type Band = 'strong' | 'moderate' | 'weak';

/** The published rule, independent of either implementation. */
function contractBand(pct: number): Band {
  if (pct >= STRONG_MIN_PCT) return 'strong';
  if (pct >= MODERATE_MIN_PCT) return 'moderate';
  return 'weak';
}

interface GoldenChart {
  readonly yogas?: readonly YogaData[];
}

/** Every yoga the engine emitted across the golden charts, tagged by chart. */
function goldenYogas(): { birth: string; yoga: YogaData }[] {
  const charts = JSON.parse(readFileSync(GOLDEN_PATH, 'utf8')) as Record<string, GoldenChart>;
  return Object.entries(charts).flatMap(([birth, chart]) =>
    (chart.yogas ?? []).map((yoga) => ({ birth, yoga })),
  );
}

const YOGAS = goldenYogas();

describe('yoga grade — the engine word and the rendered percentage are one rule', () => {
  it('reads a golden that is a real oracle, not an empty or one-sided one', () => {
    // A green agreement suite over 3 all-"moderate" yogas would prove nothing.
    expect(YOGAS.length).toBeGreaterThanOrEqual(50);
    const bands = new Set(YOGAS.map(({ yoga }) => contractBand(yoga.strength_pct ?? 0)));
    expect(bands).toEqual(new Set<Band>(['strong', 'moderate', 'weak']));
    for (const { birth, yoga } of YOGAS) {
      // If this ever goes false the suite would silently stop checking anything.
      expect(hasStrength(yoga), `${birth} / ${yoga.name} carries no calibrated strength`).toBe(true);
    }
  });

  it('renders, for every engine yoga, a word that matches its own percentage', () => {
    for (const { birth, yoga } of YOGAS) {
      const pct = yoga.strength_pct ?? 0;
      const view = yogaStrength(yoga);
      expect(
        view.band,
        `${birth} / ${yoga.name}: the report prints ${pct}%, which reads ` +
          `'${contractBand(pct)}' by the published cut points, next to the word ` +
          `'${view.band}' the engine emitted`,
      ).toBe(contractBand(pct));
    }
  });

  it('never displays a rounded percentage that implies a different word', () => {
    for (const { birth, yoga } of YOGAS) {
      const view = yogaStrength(yoga);
      expect(
        contractBand(view.pct),
        `${birth} / ${yoga.name}: ${yoga.strength_pct}% displays as ${view.pct}%, ` +
          `which crosses a cut point`,
      ).toBe(view.band);
    }
  });

  it('prints a scale the reader can reproduce the percentage from', () => {
    // The transparency half of the same defect: the ledger used to print one
    // bound ("net +0 of max +3") while the engine divides by the full span, so
    // 0/3 = 0% could not reproduce a printed 50%.
    for (const { birth, yoga } of YOGAS) {
      const view = yogaStrength(yoga);
      const reproduced = Math.round((100 * (view.net - view.min)) / (view.max - view.min));
      expect(
        reproduced,
        `${birth} / ${yoga.name}: printed "net ${view.net} on the ${view.min}…${view.max} ` +
          `scale" computes to ${reproduced}%, but the report prints ${view.pct}%`,
      ).toBe(view.pct);
    }
  });
});
